/*
   This script creates the table shopify_orders under the "sources" schema.
   https://docs.dataform.co/guides/datasets/
*/

config {
  type: "incremental",
  schema: "sources",
  tags: ["sources", "daily"],
  uniqueKey: ["id"]
}

SELECT id AS id,
       date AS date,
       customer_id AS customer_id,
       status AS status,
       payment_id AS payment_id,
       item_count AS item_count
FROM
  shopify.orders

${when(incremental(), `where date > "2020-01-01"`)}